language: ruby
rvm:
- ree
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.0
branches:
  only:
  - master
before_script:
- "sudo ./bin/setup-travis-ci.sh"
notifications:
  irc:
    channels:
    - "irc.freenode.net#jovelabs"
    use_notice: true
    skip_join: true
