language: ruby
rvm:
  - 2.0.0
  - 2.2.4
  - 2.3.0
branches:
  only:
  - master
before_install:
- "./spec/support/before_install.sh"
notifications:
  irc:
    channels:
    - "irc.freenode.net#jovelabs"
    use_notice: true
    skip_join: true
addons:
    code_climate:
        repo_token: 5bfff36fe2faa17f9251e2e5cebc5b7fb277fa58f49e6d84451f8a1a0329da0d
